# Lecture 2: More Data Structures

Raghavendra Selvan 
(raghav@di.ku.dk)

### Task 1: List Indexing and Operations

Pythonic way of indexing elements in a list can be very handy in manipulations. The advanced indexing it allows is applicable from lists to arrays and now is applicable to even tensors.

In [1]:
# Bringing back the list from previous exercise again

nus = [1,2,3,4,5,6,7,8]

# Print the length of this list
(len(nus))
# Print only the second element list 
print(nus[1])
# Print the last element
print(nus[-1])
# Print every other element, starting from the first
print(nus[::2])
# Print every other element, starting from the second
print(nus[1::2])
# Print the first 3 elements
print(nus[:3])
# Print the last 5 elements
print(nus[-5:])

2
8
[1, 3, 5, 7]
[2, 4, 6, 8]
[1, 2, 3]
[4, 5, 6, 7, 8]


In [6]:
# New random array 
nus = [5, 8, 3, 9, 1, 0, 4]

# Use dir() on this list and check what operations are permitted
print(dir(nus))

# Print a sorted list

print(sorted(nus))

# Print a reverse sorted list
print(nus[::-1])

# Append the list with a another integer
nus = nus+[100]
print(nus)

# Use any other inbuilt function that you find interesting!


['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
[0, 1, 3, 4, 5, 8, 9]
[4, 0, 1, 9, 3, 8, 5]
[5, 8, 3, 9, 1, 0, 4, 100]



### Task 2: List of Strings and methods

Another useful datatype is the string type. Strings can be populated into lists, and other than some of the manipulations we were perform above, some string specialised methods allow for complex manipulations. 

In [51]:
nordics = ['Denmark', 'Finland', 'Iceland', 'Norway', 'Sweden']

In [66]:
'land' in nordics[1]

True

In [9]:
# A sample string list 

nordics = ['Denmark', 'Finland', 'Iceland', 'Norway', 'Sweden']

# Print each country in a separate line

for i in range(len(nordics)):
    print(nordics[i])

for i in nordics:
    print(i)
 
# Print a reverse sorted list
print(sorted(nordics,reverse=True))

# Print only the first 3 characters of each country
for country in nordics:
    print(country[:3])
    
# Check which of the entries has 'land' in it
for country in nordics:
    if ( ('land' in country) & (len(country) == 7) ):
        print(country)
    else:
        print('No land in %s and does not have 7 letters!'%country)
    

# Create a new list with capitals of nordics

capitals = ['Copenhagen', 'Helsinki', 'Rejkjavik', 'Oslo', 'Stockholm']

# How would you combine the two lists into a new one? 
new_list = nordics+capitals
print(new_list)

# Again investigate what other methods are available

Denmark
Finland
Iceland
Norway
Sweden
Denmark
Finland
Iceland
Norway
Sweden
['Sweden', 'Norway', 'Iceland', 'Finland', 'Denmark']
Den
Fin
Ice
Nor
Swe
No land in Denmark and does not have 7 letters!
Finland
Iceland
No land in Norway and does not have 7 letters!
No land in Sweden and does not have 7 letters!
['Denmark', 'Finland', 'Iceland', 'Norway', 'Sweden', 'Copenhagen', 'Helsinki', 'Rejkjavik', 'Oslo', 'Stockholm']


In [10]:
# Create a new list where each entry is with country_capital: 
#Ex: 'Denmark_Copenhagen', ....

for i in range(len(nordics)):
    print(nordics[i]+'_'+capitals[i])
    
for country,city in zip(nordics,capitals):
    print(country+'_'+city)

Denmark_Copenhagen
Finland_Helsinki
Iceland_Rejkjavik
Norway_Oslo
Sweden_Stockholm
Denmark_Copenhagen
Finland_Helsinki
Iceland_Rejkjavik
Norway_Oslo
Sweden_Stockholm


In [ ]:
# Easy Printing 

# Using the two lists, print statements like 
#"The capital of Iceland is Rejkjavik", for each country


### Task 3: List comprehension

Lists that we encountered above can be used to run complex functions and save the outputs in the same list. 

Syntax: \[expression for item in list \]

In [17]:
# Given the first two elements of the Fibonacci series, 
# using list comprehension extend this list to have the first
# 20 in the sequence
a = [1,1]

[a.append(a[-1]+a[-2]) for i in range(20)]
print(a)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711]


### Task 4: Arrays with numpy

We have by now seen different datatypes. One of the most commonly encountered datatype is the numerical array. Python has a specialised library with some of the most powerful indexing and advanced methods packaged in numPy. This is an unmissable package that unleashes a trove of possibilities. We delve into some basics here.

In [ ]:
# Numpy is not a built-in package; it has to be loaded
import numpy as np 
# This is a standard way of importing packages
# And you can import a package using another identifier, 
# here numpy is being loaded as np. 

# Once you have numpy loaded, a tab after np. should show
# tons of powerful functions that are now at your finger tips

# Don't be shy! Read the docs. Invoke any intriguing function
# with its help(np.any_function_you_wish)
# Ex: help(np.random)

In [33]:
import numpy as np

In [34]:
# A numerical list has to be cast explicitly as a numpy array

# Our good old numerical list
nus = [1,2,3,4,5,6,7,8]

# Check what is its type
print(type(nus))
nus
# Now let us cast it as a numpy array
# Use dir or tab after nus to see what methods and functions are available

arr = np.array(nus)
type(arr)


<class 'list'>


numpy.ndarray

In [35]:
# Create a 4x4 array of zeros

npZeros = np.array([[0,0,0,0],
                   [0,0,0,0],
                   [0,0,0,0],
                  [0,0,0,0]])

npZeros = np.zeros((4,4))

# Create a 4x4 array of ones

npOnes = np.ones((4,4))
print(npOnes)
# Create a 4x4 diagonal matrix with 1 as diagonal entries
npDiag = np.eye(4)
print(npDiag)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
npDiag = np.diag([1,2,13,19])
npDiag

array([[ 1,  0,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  0, 13,  0],
       [ 0,  0,  0, 19]])

In [37]:
import numpy as np
np.random.seed(42)

In [38]:
# More numpy-ing

# Create a random integer matrix, with entries between 0-9,
# of size 4x4 
arr1 = np.random.randint(0,10,(4,4))
# Print the matrix
print(arr1)

# Print only the first column
print(arr1[:,0])
# Print the last row
print(arr1[-1,:])

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]]
[6 6 7 7]
[7 2 5 4]


In [39]:
# Make transpose of the matrix
print(np.transpose(arr1))
arr1.T

[[6 6 7 7]
 [3 9 4 2]
 [7 2 3 5]
 [4 6 7 4]]


array([[6, 6, 7, 7],
       [3, 9, 4, 2],
       [7, 2, 3, 5],
       [4, 6, 7, 4]])

In [40]:
print(arr1)
# Compute the mean value

# Compute row-wise mean
print(np.mean(arr1,axis=1))

# Compute column-wise mean

np.mean(arr1,axis=0)

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]]
[5.   5.75 5.25 4.5 ]


array([6.5 , 4.5 , 4.25, 5.25])

In [41]:
# Create another matrix of dimensions 4x4
arr2 = np.random.randint(0,20,(4,4))

# Compute the element-wise product of the two matrices
print(arr1 * arr2)


# Compute the matrix product of the two matrices
print(arr1.dot(arr2))


[[  6  33  35   4]
 [  0  99  22  96]
 [ 63  60  42  98]
 [126  22  95   8]]
[[141 248 237 160]
 [132 261 271 190]
 [160 243 254 127]
 [124 218 203 117]]


In [54]:
# Create a new random matrix of size 1x12
arr = np.random.randint(0,20,(1,12))
# Reshape it into a 2D array of size 3x4 
arr.reshape(3,-1)
# Reshape it into a 3d array of size 2x2x3
print(arr)


[[16 16 11 13  5  2  8  4 16 13  2  0]]


In [55]:
# Reshape it into a 3d array of size 2x2x3
arr.reshape((2,2,-1))

array([[[16, 16, 11],
        [13,  5,  2]],

       [[ 8,  4, 16],
        [13,  2,  0]]])

### Linear Algebra module in Numpy Package

Most commonly used linear algebra operations are efficiently implemented in Numpy under the linalg package. We will explore very basic functionalities here.

In [ ]:
# While you can use all linear algebra functions using np.linalg.... 
# it quickly gets tedious. 

# Instead, you can also import just linalg as
from numpy import linalg as la

In [ ]:
# Given a square matrix 
arr = np.random.randint(10,size=(4,4))

# Compute the eigen values and eigen vectors using an appropriate 
# function from linalg module


# Compute the inverse of the matrix
# Verify if the product of the matrix with its inverse
# yields an identity matrix


## More datatypes

Due to time constraint we have not looked at two other commonly encountered datatypes: tuples and dictionaries.

Some self-exercises here can highlight their purpose and features.

## Tuples

In [ ]:
# Declaring a tuple

tup = (1,2,3) 

# Check the type
print(type(tup))

In [ ]:
# Append a new element to this tuple
tup.append(4)

# Did it work? 
# How else could we do it?


In [ ]:
# One reason is that tuples are immutable; you can however concatenate a new
# tuple 

# Let's try:
tup = (tup) + (4,)

# Did this work? 

### Dictionaries
Useful look-up tables with keys and values can be built using dictionary datatypes.

Duplicate keys are not allowed!

In [18]:
# First let's create lists with all data

names = ['Me','Someone else','The other']

ages = [30,40,10]

height = [150, 160, 200]

In [19]:
allData = {'names': names,
           'ages' : ages,
           'height':height
          }

In [20]:
print(allData['names'][0])

Me


In [23]:
# Some example dictionaries

symbol_to_name = {"H": "hydrogen", "He": "helium", "Li": "lithium", "C": "carbon", "O": "oxygen", "N": "nitrogen"}

atomic_number_to_name = {1: "hydrogen", 6: "carbon", 7: "nitrogen", 8: "oxygen"}

nobel_prize_winners = {
    (1979, "physics"): ["Glashow", "Salam", "Weinberg"],
    (1962, "chemistry"): ["Hodgkin"],
    (1984, "biology"): ["McClintock"]}

# Print them to see how they are stored
print(symbol_to_name)
print(atomic_number_to_name)
print(nobel_prize_winners)

{'H': 'hydrogen', 'He': 'helium', 'Li': 'lithium', 'C': 'carbon', 'O': 'oxygen', 'N': 'nitrogen'}
{1: 'hydrogen', 6: 'carbon', 7: 'nitrogen', 8: 'oxygen'}
{(1979, 'physics'): ['Glashow', 'Salam', 'Weinberg'], (1962, 'chemistry'): ['Hodgkin'], (1984, 'biology'): ['McClintock']}


In [24]:
# Access values by specifying keys

# What is the output of 
symbol_to_name['H']

'hydrogen'

In [25]:
# Logical statements checking for entries
"O" in symbol_to_name, "U" in symbol_to_name

(True, False)

In [26]:
# Print all keys
symbol_to_name.keys()

dict_keys(['H', 'He', 'Li', 'C', 'O', 'N'])

In [27]:
# Print all values 
symbol_to_name.values()


dict_values(['hydrogen', 'helium', 'lithium', 'carbon', 'oxygen', 'nitrogen'])

In [31]:
# Updating the dictionary with additions and deletions
symbol_to_name.update({"P": "phosphorous", "S": "sulfur"})

del symbol_to_name['C']

symbol_to_name

{'H': 'hydrogen',
 'He': 'helium',
 'Li': 'lithium',
 'O': 'oxygen',
 'N': 'nitrogen',
 'P': 'phosphorous',
 'S': 'sulfur'}